### ISSUE TITLE
Type declarations don't need to be node-specific?

### ISSUE THREAD

**Issue by manzt** [gzuidhof/zarr.js#25]
@pikapkg had an example with automatic type declarations for deno via their CDN. I tried `v0.1.5` and ran into an issue (which pika fixed for us!), but there is still and issue that the author noted:

> "Looks like there's another issue behind [zarr], where Deno doesn't know what to do when it sees:

> `/// <reference types="node" />`

> You may want to look into removing that anyway, since it doesn't look like your package is node-specific."

Relevant twitter [thread](https://twitter.com/FredKSchott/status/1225478597911015424). Thanks to @FredKSchott for the quick fix and suggestion!

**Comment by FredKSchott** [comment]
Of course! I followed up your tweet by making a change to strip that `reference type="node"` directive from our response entirely for now, since the error it gives you with Deno is pretty unhelpful. Here's the latest when running Zara on Deno:

<img width="1098" alt="Screen Shot 2020-02-06 at 10 41 21 AM" src="https://user-images.githubusercontent.com/622227/73972872-64d36c00-48d6-11ea-8397-89aff55d230e.png">

Your issues seem to be entirely around Buffer. If you can remove that or replace it with some cross-platform buffer package, then everything should run smoothly.

**Comment by manzt** [comment]
Yes, this is very helpful (compared to error message earlier today)! Thanks. We have been trying to come up with a solutions for this very problem, dealing with `Buffer` and `fetch` (#21 #5) specifically, but have been wanted to avoid more libraries / polyfills.
